/**
 * FILE: src/app/payroll/page.jsx
 *
 * Kenya 2026-compliant Payroll Management
 * Generate payroll runs, view full payslips per employee,
 * approve and mark as paid. Full statutory breakdown.
 */

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  DollarSign, Play, CheckCircle2, Clock, ChevronDown,
  FileText, Users, TrendingUp, AlertCircle, X, Shield,
  Download, RefreshCw, ArrowRight, Calendar,
} from "lucide-react";
import { useState } from "react";

const MONTHS = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

const STATUS_STYLES = {
  draft:    { cls: "bg-slate-100 text-slate-600",   label: "Draft",    icon: Clock },
  approved: { cls: "bg-amber-100 text-amber-700",   label: "Approved", icon: Shield },
  paid:     { cls: "bg-emerald-100 text-emerald-700", label: "Paid",   icon: CheckCircle2 },
};

function kes(n) {
  return `KES ${Number(n || 0).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

// ── Payslip Modal ──────────────────────────────────────────────────────────
function PayslipModal({ item, run, onClose }) {
  if (!item) return null;

  function exportPayslip() {
    const content = `
AFYACORE PAYSLIP — ${MONTHS[run.period_month - 1]} ${run.period_year}
================================================================
Staff:          ${item.name}
Email:          ${item.email}
Staff No:       ${item.staff_number || "—"}
Department:     ${item.department_name || "—"}
Role:           ${item.role}

EARNINGS
--------
Basic Salary:                ${kes(item.basic_salary)}
Allowances:                  ${kes(item.allowances)}
GROSS PAY:                   ${kes(item.gross_pay)}

DEDUCTIONS
----------
NSSF (Employee 6%):          ${kes(item.nssf_employee)}
SHIF (2.75%):                ${kes(item.shif_deduction)}
Housing Levy (1.5%):         ${kes(item.housing_levy_emp)}
PAYE (after KES 2,400 relief): ${kes(item.paye)}
Other Deductions:            ${kes(item.other_deductions)}
TOTAL DEDUCTIONS:            ${kes(item.nssf_employee + item.shif_deduction + item.housing_levy_emp + item.paye + item.other_deductions)}

NET PAY:                     ${kes(item.net_pay)}

EMPLOYER CONTRIBUTIONS
----------------------
NSSF (Employer 6%):          ${kes(item.nssf_employer)}
Housing Levy (Employer 1.5%): ${kes(item.housing_levy_er)}

TAXABLE PAY COMPUTATION
-----------------------
Gross Pay:                   ${kes(item.gross_pay)}
Less NSSF:                  (${kes(item.nssf_employee)})
Taxable Pay:                 ${kes(item.taxable_pay)}
PAYE Before Relief:          ${kes(item.paye_before_relief)}
Personal Relief:            (${kes(item.personal_relief)})
Net PAYE:                    ${kes(item.paye)}

Generated by AfyaCore HMS | ${new Date().toLocaleString("en-KE")}
    `.trim();
    const blob = new Blob([content], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href = url; a.download = `payslip-${item.staff_number || item.name}-${run.period_year}-${String(run.period_month).padStart(2,"0")}.txt`;
    a.click(); URL.revokeObjectURL(url);
  }

  const totalDeductions = item.nssf_employee + item.shif_deduction + item.housing_levy_emp + item.paye + item.other_deductions;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="w-full max-w-md rounded-2xl bg-white shadow-2xl overflow-hidden max-h-[90vh] flex flex-col">
        <div className="flex items-start justify-between border-b border-slate-100 bg-[#0F172A] px-6 py-4">
          <div>
            <p className="text-xs text-slate-400 uppercase tracking-widest font-bold">Payslip</p>
            <h2 className="text-lg font-bold text-white">{item.name}</h2>
            <p className="text-xs text-slate-400">{MONTHS[run.period_month-1]} {run.period_year} · {item.staff_number || ""}</p>
          </div>
          <button onClick={onClose} className="rounded-lg p-1.5 text-slate-400 hover:bg-white/10"><X size={18} /></button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-5">
          {/* Earnings */}
          <Section title="Earnings">
            <Row label="Basic Salary"   value={kes(item.basic_salary)} />
            <Row label="Allowances"     value={kes(item.allowances)} />
            <Row label="Gross Pay" value={kes(item.gross_pay)} bold accent="emerald" />
          </Section>

          {/* Deductions */}
          <Section title="Statutory Deductions">
            <Row label="NSSF (Employee 6%)"          value={`(${kes(item.nssf_employee)})`} negative />
            <Row label="SHIF (2.75%)"                value={`(${kes(item.shif_deduction)})`} negative />
            <Row label="Housing Levy (1.5%)"          value={`(${kes(item.housing_levy_emp)})`} negative />
            <Row label="PAYE"                         value={`(${kes(item.paye)})`} negative />
            {item.other_deductions > 0 && <Row label="Other Deductions" value={`(${kes(item.other_deductions)})`} negative />}
            <Row label="Total Deductions" value={`(${kes(totalDeductions)})`} bold accent="red" />
          </Section>

          {/* Net */}
          <div className="rounded-xl bg-emerald-600 p-4 text-white flex items-center justify-between">
            <span className="font-bold">NET PAY</span>
            <span className="text-xl font-bold font-mono">{kes(item.net_pay)}</span>
          </div>

          {/* PAYE breakdown */}
          <Section title="PAYE Computation">
            <Row label="Gross Pay"           value={kes(item.gross_pay)} />
            <Row label="Less: NSSF"          value={`(${kes(item.nssf_employee)})`} />
            <Row label="Taxable Pay"         value={kes(item.taxable_pay)} />
            <Row label="Tax on Taxable Pay"  value={kes(item.paye_before_relief)} />
            <Row label="Personal Relief"     value={`(${kes(item.personal_relief)})`} />
            <Row label="Net PAYE"            value={kes(item.paye)} bold />
          </Section>

          {/* Employer cost */}
          <Section title="Employer's Portion">
            <Row label="NSSF (Employer 6%)"          value={kes(item.nssf_employer)} />
            <Row label="Housing Levy (Employer 1.5%)" value={kes(item.housing_levy_er)} />
            <Row label="Total Employer Cost" value={kes(parseFloat(item.gross_pay) + parseFloat(item.nssf_employer) + parseFloat(item.housing_levy_er))} bold accent="slate" />
          </Section>

          <p className="text-[10px] text-slate-400 text-center">Kenya Revenue Authority (KRA) 2026 rates applied. Personal relief: KES 2,400/month.</p>
        </div>

        <div className="border-t border-slate-100 bg-slate-50 px-6 py-3">
          <button onClick={exportPayslip}
            className="flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">
            <Download size={15} /> Download Payslip (.txt)
          </button>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">{title}</p>
      <div className="rounded-xl border border-slate-100 bg-slate-50 overflow-hidden divide-y divide-slate-100">
        {children}
      </div>
    </div>
  );
}

function Row({ label, value, bold, negative, accent }) {
  const accentColors = {
    emerald: "text-emerald-700",
    red:     "text-red-600",
    slate:   "text-slate-700",
  };
  return (
    <div className="flex justify-between items-center px-4 py-2.5">
      <span className={`text-sm ${bold ? "font-bold text-[#0F172A]" : "text-slate-600"}`}>{label}</span>
      <span className={`font-mono text-sm ${bold ? "font-bold " + (accentColors[accent] || "text-[#0F172A]") : negative ? "text-red-600" : "text-[#0F172A]"}`}>{value}</span>
    </div>
  );
}

// ── Main Page ───────────────────────────────────────────────────────────────
export default function PayrollPage() {
  const qc = useQueryClient();
  const now = new Date();
  const [genMonth, setGenMonth] = useState(now.getMonth() + 1);
  const [genYear,  setGenYear]  = useState(now.getFullYear());
  const [selectedRun, setSelectedRun] = useState(null);
  const [selectedPayslip, setSelectedPayslip] = useState(null);

  // List runs
  const { data: runsData, isLoading: runsLoading } = useQuery({
    queryKey: ["payroll-runs"],
    queryFn: async () => {
      const res = await fetch("/api/payroll");
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
  });

  // Run detail
  const { data: runDetail, isLoading: detailLoading } = useQuery({
    queryKey: ["payroll-detail", selectedRun],
    queryFn: async () => {
      const res = await fetch(`/api/payroll?runId=${selectedRun}`);
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
    enabled: !!selectedRun,
  });

  const generate = useMutation({
    mutationFn: async () => {
      const res = await fetch("/api/payroll", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ month: genMonth, year: genYear }),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error || "Failed to generate payroll");
      return d;
    },
    onSuccess: (d) => {
      qc.invalidateQueries(["payroll-runs"]);
      setSelectedRun(d.runId);
    },
  });

  const approve = useMutation({
    mutationFn: async ({ runId, action }) => {
      const res = await fetch("/api/payroll", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ runId, action }),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error || "Failed");
      return d;
    },
    onSuccess: () => {
      qc.invalidateQueries(["payroll-runs"]);
      qc.invalidateQueries(["payroll-detail", selectedRun]);
    },
  });

  const runs  = runsData?.runs || [];
  const run   = runDetail?.run;
  const items = runDetail?.items || [];

  function exportRunCSV() {
    if (!items.length) return;
    const headers = ["Staff No","Name","Dept","Basic","Allowances","Gross","NSSF(Emp)","SHIF","Housing","PAYE","Other","Net Pay","NSSF(Er)","Housing(Er)"];
    const rows = items.map(i => [
      i.staff_number,i.name,i.department_name||"",
      i.basic_salary,i.allowances,i.gross_pay,
      i.nssf_employee,i.shif_deduction,i.housing_levy_emp,
      i.paye,i.other_deductions,i.net_pay,
      i.nssf_employer,i.housing_levy_er,
    ]);
    const csv = [headers,...rows].map(r=>r.map(c=>`"${(c||"").toString().replace(/"/g,'""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], {type:"text/csv"});
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href=url; a.download=`payroll-${run.period_year}-${String(run.period_month).padStart(2,"0")}.csv`;
    a.click(); URL.revokeObjectURL(url);
  }

  const activeRun = runs.find(r => r.id === selectedRun) || run;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-[#0F172A]">Payroll Management</h1>
          <p className="text-sm text-[#64748B]">Kenya 2026 statutory calculations — PAYE, NSSF, SHIF, Housing Levy</p>
        </div>
        {/* Generate control */}
        <div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-2 shadow-sm">
          <select value={genMonth} onChange={e => setGenMonth(+e.target.value)}
            className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-1.5 text-sm outline-none">
            {MONTHS.map((m,i) => <option key={i} value={i+1}>{m}</option>)}
          </select>
          <input type="number" value={genYear} onChange={e => setGenYear(+e.target.value)}
            className="w-20 rounded-lg border border-slate-200 bg-slate-50 px-3 py-1.5 text-sm outline-none text-center" />
          <button onClick={() => generate.mutate()} disabled={generate.isPending}
            className="flex items-center gap-1.5 rounded-lg bg-[#0F172A] px-4 py-1.5 text-sm font-semibold text-white hover:bg-[#1E293B] disabled:opacity-50">
            <Play size={14} /> {generate.isPending ? "Generating…" : "Generate"}
          </button>
        </div>
      </div>

      {generate.isError && (
        <div className="flex items-center gap-2 rounded-xl bg-red-50 border border-red-200 p-3 text-sm text-red-700">
          <AlertCircle size={16} /> {generate.error.message}
        </div>
      )}

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* Runs list */}
        <div className="lg:col-span-1">
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
            <div className="border-b border-slate-100 bg-slate-50 px-4 py-3">
              <h3 className="font-bold text-sm text-[#0F172A] flex items-center gap-2">
                <Calendar size={16} className="text-slate-400" /> Payroll Periods
              </h3>
            </div>
            {runsLoading ? (
              <div className="p-4 space-y-2">
                {[...Array(4)].map((_,i) => <div key={i} className="h-14 animate-pulse rounded-xl bg-slate-100" />)}
              </div>
            ) : runs.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-center px-4">
                <DollarSign size={32} className="text-slate-200 mb-3" />
                <p className="text-sm font-bold text-slate-400">No payroll runs yet</p>
                <p className="text-xs text-slate-400">Generate your first payroll using the controls above.</p>
              </div>
            ) : (
              <div className="divide-y divide-slate-50">
                {runs.map((r) => {
                  const st = STATUS_STYLES[r.status] || STATUS_STYLES.draft;
                  const Icon = st.icon;
                  const isActive = r.id === selectedRun;
                  return (
                    <button key={r.id} onClick={() => setSelectedRun(r.id)}
                      className={`w-full flex items-center justify-between px-4 py-3.5 text-left transition-all hover:bg-slate-50 ${isActive ? "bg-[#0F172A]/5 border-l-4 border-[#0F172A]" : ""}`}>
                      <div>
                        <p className="font-semibold text-sm text-[#0F172A]">{MONTHS[r.period_month-1]} {r.period_year}</p>
                        <p className="text-xs text-slate-500 font-mono">{kes(r.total_net)} net</p>
                      </div>
                      <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-bold ${st.cls}`}>
                        <Icon size={10} /> {st.label}
                      </span>
                    </button>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Run detail */}
        <div className="lg:col-span-2">
          {!selectedRun ? (
            <div className="flex flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 py-24 text-center">
              <ArrowRight size={32} className="text-slate-200 mb-3" />
              <p className="font-bold text-slate-400">Select a payroll period to view details</p>
              <p className="text-sm text-slate-400">Or generate a new one for the current period.</p>
            </div>
          ) : detailLoading ? (
            <div className="space-y-3">
              {[...Array(4)].map((_,i) => <div key={i} className="h-16 animate-pulse rounded-xl bg-slate-100" />)}
            </div>
          ) : run && (
            <div className="space-y-4">
              {/* Run summary card */}
              <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between mb-5">
                  <div>
                    <h2 className="text-lg font-bold text-[#0F172A]">{MONTHS[run.period_month-1]} {run.period_year} Payroll</h2>
                    <p className="text-xs text-slate-500">{items.length} employees · Generated by {run.created_by_name}</p>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    {run.status === "draft" && (
                      <button onClick={() => approve.mutate({ runId: run.id, action: "approve" })}
                        disabled={approve.isPending}
                        className="flex items-center gap-1.5 rounded-xl bg-amber-500 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-600 disabled:opacity-50">
                        <Shield size={14} /> Approve
                      </button>
                    )}
                    {run.status === "approved" && (
                      <button onClick={() => approve.mutate({ runId: run.id, action: "mark_paid" })}
                        disabled={approve.isPending}
                        className="flex items-center gap-1.5 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50">
                        <CheckCircle2 size={14} /> Mark Paid
                      </button>
                    )}
                    {run.status === "draft" && (
                      <button onClick={() => generate.mutate()} disabled={generate.isPending}
                        className="flex items-center gap-1.5 rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">
                        <RefreshCw size={14} /> Recalculate
                      </button>
                    )}
                    <button onClick={exportRunCSV}
                      className="flex items-center gap-1.5 rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">
                      <Download size={14} /> CSV
                    </button>
                  </div>
                </div>

                {/* Totals */}
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                  {[
                    ["Total Gross",    run.total_gross,   "bg-slate-50"],
                    ["Total PAYE",     run.total_paye,    "bg-red-50"],
                    ["Total NSSF",     run.total_nssf,    "bg-amber-50"],
                    ["Total SHIF",     run.total_shif,    "bg-purple-50"],
                    ["Housing Levy",   run.total_housing, "bg-blue-50"],
                    ["Total Net Pay",  run.total_net,     "bg-emerald-50"],
                  ].map(([label, val, bg]) => (
                    <div key={label} className={`rounded-xl p-3 ${bg}`}>
                      <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p>
                      <p className={`mt-1 font-mono font-bold text-sm ${label === "Total Net Pay" ? "text-emerald-700" : "text-[#0F172A]"}`}>{kes(val)}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Employee table */}
              <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                <div className="border-b border-slate-100 bg-slate-50 px-4 py-3 flex items-center justify-between">
                  <h3 className="font-bold text-sm text-[#0F172A] flex items-center gap-2">
                    <Users size={16} className="text-slate-400" /> Employee Breakdown
                  </h3>
                  <p className="text-xs text-slate-500">{items.length} employees</p>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="border-b border-slate-100 bg-slate-50/50">
                        {["Name","Gross","NSSF","SHIF","Housing","PAYE","Net Pay",""].map(h => (
                          <th key={h} className="px-3 py-2.5 text-left font-bold uppercase tracking-wider text-[10px] text-slate-400">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-50">
                      {items.map((item) => (
                        <tr key={item.id} className="hover:bg-slate-50 transition-colors">
                          <td className="px-3 py-2.5">
                            <div className="font-semibold text-[#0F172A]">{item.name}</div>
                            <div className="text-[10px] text-slate-400">{item.department_name || item.role}</div>
                          </td>
                          <td className="px-3 py-2.5 font-mono text-slate-700">{kes(item.gross_pay)}</td>
                          <td className="px-3 py-2.5 font-mono text-red-600">({kes(item.nssf_employee)})</td>
                          <td className="px-3 py-2.5 font-mono text-red-600">({kes(item.shif_deduction)})</td>
                          <td className="px-3 py-2.5 font-mono text-red-600">({kes(item.housing_levy_emp)})</td>
                          <td className="px-3 py-2.5 font-mono text-red-600">({kes(item.paye)})</td>
                          <td className="px-3 py-2.5 font-mono font-bold text-emerald-700">{kes(item.net_pay)}</td>
                          <td className="px-3 py-2.5">
                            <button onClick={() => setSelectedPayslip(item)}
                              className="rounded-lg border border-slate-200 px-2 py-1 text-[10px] font-bold text-slate-600 hover:bg-slate-100 whitespace-nowrap">
                              <FileText size={12} className="inline mr-0.5" /> Payslip
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {selectedPayslip && (
        <PayslipModal item={selectedPayslip} run={activeRun || run} onClose={() => setSelectedPayslip(null)} />
      )}
    </div>
  );
}